Reimplement the Authorization header rewriter for the Documents app
civicsource/webapi-utils pull request #10
Opened 2018-08-13 19:56 UTC by tullo-x86

This got missed when splitting Archon.Http out to server and client libraries. It's been re-added, and the usage documentation has been updated.

2018-08-13 20:04 UTC, chadly approved these changes

2018-08-13 20:05 UTC, chadly requested changes
Add a `+semver:minor` to one of the commit messages for a minor version bump.

2018-08-14 16:53 UTC, chadly approved these changes

2018-08-14 21:44 UTC, merged

2018-10-30 18:26 UTC, tullo-x86 commented
Turns out this was entirely unnecessary since this functionality was rolled into the Security client... >_>