Upgrade project to .net standard 1.3
civicsource/webapi-utils pull request #2
Opened 2017-06-14 15:18 UTC by chadly

Project can be used from .net core & Asp.Net Core now. Also removing no longer necessary helper utilities due to their inclusion in Asp.Net Core.

This will also make #1 build.

2017-06-14 15:30 UTC, broline requested changes

2017-06-14 15:30 UTC, broline commented on Archon.Http.Tests/FakeHttpHandler.cs
> +	class FakeHttpHandler : HttpMessageHandler
why internal now instead of public? Are we going to stop using `FakeHttpHandler` like you were talking about?

2017-06-14 15:36 UTC, chadly commented on Archon.Http.Tests/FakeHttpHandler.cs
> +	class FakeHttpHandler : HttpMessageHandler
hmm yeah, I [removed that over a year ago](https://github.com/civicsource/http/pull/2/commits/e5423d181c78930a8eda3ba594dfd7e0e3ad391a).

I don't think we are quite ready to drop it just yet. Let me put it back.

2017-06-14 16:18 UTC, adragoset commented
Nice




On Jun 14, 2017 10:36 AM, "Chad Lee" <notifications@github.com> wrote:

*@chadly* commented on this pull request.
------------------------------

In Archon.Http.Tests/FakeHttpHandler.cs
<https://github.com/civicsource/http/pull/2#discussion_r121983571>:

>  {
-	public class FakeHttpHandler : HttpMessageHandler
+	class FakeHttpHandler : HttpMessageHandler

hmm yeah, I removed that over a year ago
<https://github.com/civicsource/http/pull/2/commits/e5423d181c78930a8eda3ba594dfd7e0e3ad391a>
.

I don't think we are quite ready to drop it just yet. Let me put it back.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/civicsource/http/pull/2#discussion_r121983571>, or mute
the thread
<https://github.com/notifications/unsubscribe-auth/ABrejk6S90arVmkVn4VcyzDffo4wRvPLks5sD_3jgaJpZM4N6Chp>
.

2017-07-21 16:29 UTC, chadly commented on Archon.Http.Tests/FakeHttpHandler.cs
> +	class FakeHttpHandler : HttpMessageHandler
Actually, thinking about this further, we probably are going to need to maintain a 1.x version branch for legacy projects anyway. In v2, we do want to remove this publicly.

I'd like to get this merged though, so I can use this in the [releases project](https://github.com/civicsource/releases) to gather github stats.

2017-07-21 16:34 UTC, broline approved these changes

2017-07-21 16:37 UTC, merged